services:
    dsm:
        container_name: dsm
        image: vdsm/virtual-dsm:latest
        environment:
            DISK_SIZE: "16G"
        devices:
            - /dev/kvm
        cap_add:
            - NET_ADMIN
        networks:
            vdsm:
                ipv4_address: 192.168.1.81  # 為 DSM 容器指定 IP，調整為可用的 IP

        volumes:
            - /var/dsm:/storage
        stop_grace_period: 2m

networks:
    vdsm:
        external: true
